export * from './menu';
export * from './social';
// export * from './howWeWork';
export * from './sidebarMenuIcons';

export { default as SunIcon } from './Sun';
export { default as ChatIcon } from './Chat';
export { default as FileIcon } from './File';
export { default as LogoIcon } from './Logo';
export { default as MoonIcon } from './Moon';
export { default as StepIcon } from './step.svg';
export { default as CrossIcon } from './cross.svg';
export { default as MouseIcon } from './Mouse';
export { default as ArrowIcon } from './arrow.svg';
export { default as SuccessIcon } from './Success';
export { default as SunHoverIcon } from './SunHover';
export { default as ArrowGdtIcon } from './arrow-gdt.svg';
export { default as MoonHoverIcon } from './MoonHover';
export { default as LogoAnimaIcon } from './LogoAnimaIcon';
export { default as LogoLargeIcon } from './logoLarge.svg';
export { default as MouseLightIcon } from './MouseLight';
export { default as LogoMoveBallIcon } from './LogoMoveBallIcon';
