export * from './menu';
export * from './social';
export * from './sidebaricons';

export { default as Spp } from './spp.svg';
export { default as SunIcon } from './Sun';
export { default as FileIcon } from './File';
export { default as LogoIcon } from './Logo';
export { default as MoonIcon } from './Moon';
export { default as StepIcon } from './step.svg';
export { default as ChatIcon } from './Chat';
export { default as KomShin } from './komShin.svg';
export { default as CrossIcon } from './cross.svg';
export { default as MouseIcon } from './Mouse';
export { default as ArrowIcon } from './arrow.svg';
export { default as SuccessIcon } from './Success';
export { default as SppLight } from './sppLight.svg';
export { default as SunHoverIcon } from './SunHover';
export { default as MoveRopeIcon } from './MoveRope';
export { default as ArrowGdtIcon } from './arrow-gdt.svg';
export { default as MoonHoverIcon } from './MoonHover';
export { default as ChatHoverIcon } from './ChatHover';
export { default as LogoAnimaIcon } from './LogoAnimaIcon';
export { default as LogoLargeIcon } from './logoLarge.svg';
export { default as DoubleOneIcon } from './doubleOne.svg';
export { default as KristobadIcon } from './kristobad.svg';
export { default as MouseLightIcon } from './MouseLight';
export { default as ArrowIconLight } from './arrowlight.svg';
export { default as IndustryTwoIcon } from './Industries-2';
export { default as AccountantIcon } from './accountantLight.svg';
export { default as IndustryThreeIcon } from './Industries-3';
export { default as IndustryFirstIcon } from './Ecommerce';
export { default as LogoMoveBallIcon } from './LogoMoveBallIcon';
export { default as AccountantLightIcon } from './accountant.svg';
export { default as MainBgIcon } from './mainBg.svg';
export { default as LongArrowIcon } from './longArrow.svg';
export { default as LinerArrowIcon } from './liner.svg';
