import {
  Section4DarkIcon,
  Section5DarkIcon,
  Section6DarkIcon,
  Section7DarkIcon,
  Section8DarkIcon,
  // Section9DarkIcon,
  Section4LigthIcon,
  Section5LigthIcon,
  Section6LigthIcon,
  Section7LigthIcon,
  Section8LigthIcon,
  // Section9LigthIcon,
  // Section10DarkIcon,
  Section11DarkIcon,
  Section5ActiveIcon,
  SectionOneDarkIcon,
  SectionTwoDarkIcon,
  Section4ActiveIcon,
  Section6ActiveIcon,
  Section7ActiveIcon,
  Section8ActiveIcon,
  // Section9ActiveIcon,
  // Section10LigthIcon,
  Section11LigthIcon,
  SectionOneLigthIcon,
  SectionTwoLigthIcon,
  // Section10ActiveIcon,
  Section11ActiveIcon,
  SectionOneActiveIcon,
  SectionTwoActiveIcon,
  SectionThreeDarkIcon,
  SectionThreeLigthIcon,
  SectionThreeActiveIcon,
} from '../icons';

const menuLinks = [
  {
    icon: SectionOneDarkIcon,
    iconLight: SectionOneLigthIcon,
    iconHover: SectionOneActiveIcon,
    sectionIndex: 1,
  },
  {
    icon: SectionTwoDarkIcon,
    iconLight: SectionTwoLigthIcon,
    iconHover: SectionTwoActiveIcon,
    sectionIndex: 2,
  },
  {
    icon: SectionThreeDarkIcon,
    iconLight: SectionThreeLigthIcon,
    iconHover: SectionThreeActiveIcon,
    sectionIndex: 3,
  },
  {
    icon: Section4DarkIcon,
    iconLight: Section4LigthIcon,
    iconHover: Section4ActiveIcon,
    sectionIndex: 4,
  },
  {
    icon: Section5DarkIcon,
    iconLight: Section5LigthIcon,
    iconHover: Section5ActiveIcon,
    sectionIndex: 5,
  },
  {
    icon: Section6DarkIcon,
    iconLight: Section6LigthIcon,
    iconHover: Section6ActiveIcon,
    sectionIndex: 6,
  },
  {
    icon: Section7DarkIcon,
    iconLight: Section7LigthIcon,
    iconHover: Section7ActiveIcon,
    sectionIndex: 7,
  },
  {
    icon: Section8DarkIcon,
    iconLight: Section8LigthIcon,
    iconHover: Section8ActiveIcon,
    sectionIndex: 8,
  },
  {
    icon: Section11DarkIcon,
    iconLight: Section11LigthIcon,
    iconHover: Section11ActiveIcon,
    sectionIndex: 9,
  },
];

export default menuLinks;
