/* eslint-disable no-unused-vars */
import shortid from 'shortid';

import {
  MapIcon,
  HomeIcon,
  TeamIcon,
  StackIcon,
  ReviewIcon,
  WeWorkIcon,
  PartnersIcon,
  LightMapIcon,
  IndustryIcon,
  ActiveMapIcon,
  LightTeamIcon,
  LightHomeIcon,
  PortfolioIcon,
  ActiveTeamIcon,
  ActiveHomeIcon,
  LightStackIcon,
  LightReviewIcon,
  ActiveStackIcon,
  TeamMembersIcon,
  InformationIcon,
  LightWeWorkIcon,
  ActiveReviewIcon,
  ActiveWeWorkIcon,
  LightPartnersIcon,
  LightIndustryIcon,
  ActivePartnersIcon,
  LightPortfolioIcon,
  ActiveIndustryIcon,
  ActivePortfolioIcon,
  LightInformationIcon,
  LightTeamMembersIcon,
  ActiveTeamMembersIcon,
  ActiveInformationIcon,
} from '../icons';

const menuLinks = [
  {
    id: shortid.generate(),
    icon: HomeIcon,
    iconLight: LightHomeIcon,
    iconHover: ActiveHomeIcon,
    sectionIndex: 1,
  },
  {
    id: shortid.generate(),
    icon: InformationIcon,
    iconLight: LightInformationIcon,
    iconHover: ActiveInformationIcon,
    sectionIndex: 2,
  },
  {
    id: shortid.generate(),
    icon: WeWorkIcon,
    iconLight: LightWeWorkIcon,
    iconHover: ActiveWeWorkIcon,
    sectionIndex: 3,
  },
  {
    id: shortid.generate(),
    icon: IndustryIcon,
    iconLight: LightIndustryIcon,
    iconHover: ActiveIndustryIcon,
    sectionIndex: 4,
  },
  {
    id: shortid.generate(),
    icon: PortfolioIcon,
    iconLight: LightPortfolioIcon,
    iconHover: ActivePortfolioIcon,
    sectionIndex: 5,
  },
  {
    id: shortid.generate(),
    icon: TeamIcon,
    iconLight: LightTeamIcon,
    iconHover: ActiveTeamIcon,
    sectionIndex: 6,
  },
  {
    id: shortid.generate(),
    icon: TeamMembersIcon,
    iconLight: LightTeamMembersIcon,
    iconHover: ActiveTeamMembersIcon,
    sectionIndex: 7,
  },
  // {
  //   id: shortid.generate(),
  //   icon: StackIcon,
  //   iconLight: LightStackIcon,
  //   iconHover: ActiveStackIcon,
  //   sectionIndex: 8,
  // },
  // {
  //   id: shortid.generate(),
  //   icon: PartnersIcon,
  //   iconLight: LightPartnersIcon,
  //   iconHover: ActivePartnersIcon,
  //   sectionIndex: 9,
  // },
  // {
  //   id: shortid.generate(),
  //   icon: ReviewIcon,
  //   iconLight: LightReviewIcon,
  //   iconHover: ActiveReviewIcon,
  //   sectionIndex: 10,
  // },
  // {
  //   id: shortid.generate(),
  //   icon: MapIcon,
  //   iconLight: LightMapIcon,
  //   iconHover: ActiveMapIcon,
  //   sectionIndex: 11,
  // },
];

export default menuLinks;
