const teamCard = [
  {
    id: 1,
    image1: '/images/team/Karo.png',
    image2: '/images/team/Karo.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Karo.png',
    imageLight1: '/images/team/KaroLight.png',
    imageLight2: '/images/team/KaroLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/KaroLight.png',
    title: 'Karo Zakaryan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 2,
    image1: '/images/team/Lyudvig.png',
    image2: '/images/team/Lyudvig.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Lyudvig.png',
    imageLight1: '/images/team/LyudvigLight.png',
    imageLight2: '/images/team/LyudvigLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/LyudvigLight.png',
    title: 'Lyudvig Grigoryan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 4,
    image1: '/images/team/Karo.png',
    image2: '/images/team/Karo.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Karo.png',
    imageLight1: '/images/team/KaroLight.png',
    imageLight2: '/images/team/KaroLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/KaroLight.png',
    title: 'Karo Zakaryan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 5,
    image1: '/images/team/Lyudvig.png',
    image2: '/images/team/Lyudvig.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Lyudvig.png',
    imageLight1: '/images/team/LyudvigLight.png',
    imageLight2: '/images/team/LyudvigLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/LyudvigLight.png',
    title: 'Lyudvig Grigoryan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 7,
    image1: '/images/team/Karo.png',
    image2: '/images/team/Karo.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Karo.png',
    imageLight1: '/images/team/KaroLight.png',
    imageLight2: '/images/team/KaroLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/KaroLight.png',
    title: 'Karo Zakaryan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 8,
    image1: '/images/team/Lyudvig.png',
    image2: '/images/team/Lyudvig.png',
    image3: '/images/team/matrixDark.jpg',
    image4: '/images/team/Lyudvig.png',
    imageLight1: '/images/team/LyudvigLight.png',
    imageLight2: '/images/team/LyudvigLight.png',
    imageLight3: '/images/team/matrixLight.jpg',
    imageLight4: '/images/team/LyudvigLight.png',
    title: 'Lyudvig Grigoryan',
    subtitle: 'FRONT-END DEVELOPER',
  },
];

export default teamCard;
