const teamCard = [
  {
    id: 1,
    image1: '/images/team/3.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/3.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Karo Zakaryan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 2,
    image1: '/images/team/1.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/1.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Mkrtich Grigoryan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 3,
    image1: '/images/team/2.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/2.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Hrant Abrahamyan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 4,
    image1: '/images/team/4.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/4.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Shant Issa',
    subtitle: 'Native DEVELOPER',
  },
  {
    id: 5,
    image1: '/images/team/5.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/5.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Henrik Armenakyan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 6,
    image1: '/images/team/7.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/7.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Eduard Noramiryan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 10,
    image1: '/images/team/6.png',
    image2: '/images/team/matrixDark.jpg',
    image3: '/images/team/6.png',
    image4: '/images/team/matrixDark.jpg',
    title: 'Varsine Pogosyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
];

export default teamCard;
