const teamCard = [
  {
    id: 1,
    image1: '/images/team/2.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/2.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Hrant Abrahamyan',
    subtitle: 'Co-Founder, CEO',
  },
  {
    id: 2,
    image1: '/images/team/3.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/3.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Karo Zakaryan',
    subtitle: 'Co-Founder, CEO',
  },
  {
    id: 3,
    image1: '/images/team/7.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/7.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Gor Meshinyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 4,
    image1: '/images/team/5.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/5.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Henrik Armenakyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 5,
    image1: '/images/team/4.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/4.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Shant Issa',
    subtitle: 'REACT-NATIVE DEVELOPER',
  },
  {
    id: 6,
    image1: '/images/team/9.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/9.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Martin Martirosyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 10,
    image1: '/images/team/10.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/10.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Edita Tonoyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 11,
    image1: '/images/team/10.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/10.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Garik Gharibyan',
    subtitle: 'QA ENGINNER',
  },
  {
    id: 7,
    image1: '/images/team/6.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/6.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Edward Noramiryan',
    subtitle: 'FULL-STACK DEVELOPER',
  },
  {
    id: 8,
    image1: '/images/team/8.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/8.webp',
    image4: '/images/team/matrixDark.webp',
    title: 'Varsine Poghosyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
  {
    id: 9,
    image1: '/images/team/1.webp',
    image2: '/images/team/matrixDark.webp',
    image3: '/images/team/1.webp',
    image4: '/images/team/matrixDark.webp',
    title: ' Mkrtich Okroyan',
    subtitle: 'FRONT-END DEVELOPER',
  },
];

export default teamCard;
